Feature/authentication (WIP)
ltrigo/mygrant pull request #29
Opened 2018-04-28 18:11 UTC by edgarlpassos

Adds authentication (sign up and log in) using email + password with PassportJS
The user receives and stores a JSON Web Token that he can send to authenticate himself on requests
(See `/as_options` route in `routes/countries.js` and the corresponding request on `client/src/containers/SignUpInfo.js` in the `componentDidMount()`function.

Adds ProtectedRoute component, which redirects the user to the login page instead of the desired page if they are not logged in. (See `signUpInfo` route on `client/src/index.js`)

**This is a WIP (most frontend missing) but can already be used to test for some features - DO NOT DELETE THIS BRANCH**

2018-04-30 08:23 UTC, diogohmcruz requested changes
Qual o motivo para mudar o nome da pasta de container para component?

2018-04-30 08:37 UTC, edgarlpassos commented
Foi o contrário, mudei de components para components + containers.
O objetivo é ter os containers (páginas completas) separadas de components (partes de páginas que possívelmente serão utilizados em mais sítios)

2018-04-30 15:15 UTC, BlueDi commented
Não acho boa ideia porque um component pode sempre ser chamado dentro de outra página. Só vai gerar confusão sobre o que é uma página inteira e o que não é.
Mais vale todos os components estarem na mesma pasta.

2018-04-30 15:26 UTC, edgarlpassos commented
@BlueDi 

Eu já tive esta discussão com o @dcepa95  e era da tua opiniao até começar a fazer esta parte do site. Esta divisão não introduz confusão, pelo contrario, sabes exatamente quais os componentes que são páginas inteiras, porque eles estarão numa pasta diferente, e não estou a ver uma situação em que uma pessoa não saiba dizer se um componente é uma página inteira ou não.

2018-04-30 18:09 UTC, BlueDi commented
Podes ter uma página para o login, ou só um pop-up.
Podes ter uma página de um user, ou so um cartão com os detalhes.
Acho que é mais simples ter uma pasta com tudo.

2018-04-30 18:31 UTC, edgarlpassos commented
@BlueDi

Não sei qual é a confusão que faz. Nesse caso colocas o pop-up de login e o cartão de utilizador nos componentes e as página nos containers, são ficheiros completamente diferentes. Qual é o problema que poderá surgir?

2018-05-01 08:08 UTC, BlueDi commented
Vê a página dos serviços como tem os modal. As páginas dos users são páginas completas que nessa página são só modais.

2018-05-01 08:54 UTC, edgarlpassos commented
Então isso não devia estar feito assim. Um modal não devia ser identico a uma página, pode ter componentes em comum, mas não ser exatamente igual.

2018-05-01 11:59 UTC, dcepa95 approved these changes
Eu concordo com a alteração da estrutura de pastas.

2018-05-01 13:59 UTC, BlueDi commented on client/src/containers/Login.js
> +import '../css/Login.css';
Falta fazer commit deste ficheiro

2018-05-01 15:32 UTC, edgarlpassos commented
The work set out for this branch is complete.
Here are some screenshots for the final result:

![screenshot from 2018-05-01 16-26-14](https://user-images.githubusercontent.com/14338539/39479421-1d8b140e-4d5d-11e8-8e78-9bafb696b856.png)
![screenshot from 2018-05-01 16-26-30](https://user-images.githubusercontent.com/14338539/39479422-1dce6d12-4d5d-11e8-8ef5-51990519612b.png)
![screenshot from 2018-05-01 16-27-08](https://user-images.githubusercontent.com/14338539/39479423-1df251be-4d5d-11e8-8959-8364c3b3c576.png)
![screenshot from 2018-05-01 16-27-29](https://user-images.githubusercontent.com/14338539/39479424-1e13743e-4d5d-11e8-9e56-05d93370347b.png)
![screenshot from 2018-05-01 16-27-52](https://user-images.githubusercontent.com/14338539/39479425-1e32526e-4d5d-11e8-90c7-42892b95a0c9.png)
![screenshot from 2018-05-01 16-28-27](https://user-images.githubusercontent.com/14338539/39479426-1e6bb3ce-4d5d-11e8-9f29-1f4a56cb5da1.png)
![screenshot from 2018-05-01 16-28-45](https://user-images.githubusercontent.com/14338539/39479427-1e8db334-4d5d-11e8-936a-91bfaf1dd4d9.png)

**This branch can be safely deleted**

2018-05-01 15:56 UTC, diogohmcruz approved these changes

2018-05-01 17:23 UTC, merged