Default Express port 3001
ltrigo/mygrant pull request #5
Opened 2018-04-09 09:50 UTC by BlueDi

Não sei se é preciso o PORT para o travis ou o nanobox, mas localmente não me deixa correr com ele.

2018-04-09 10:19 UTC, diogohmcruz commented
https://stackoverflow.com/a/44473239/7150521
Ao que parece a versão Windows é diferente.
Mas se der para mudar para uma versão universal sem ter que definir o port no comando melhor.

2018-04-09 14:31 UTC, diogoseca requested changes
A maior parte deste commit vai causar problemas na indentação (o actual é de 2 espaços, não de 8!!)

2018-04-11 16:51 UTC, diogohmcruz commented
@diogoseca já mudei o espaçamento para 4 espaços nestes ficheiros.

2018-04-11 17:12 UTC, diogoseca approved these changes

2018-04-11 17:13 UTC, merged