Profile almost done (missing edit)
ltrigo/mygrant pull request #51
Opened 2018-05-18 13:43 UTC by BSantos22

2018-05-21 14:02 UTC, Evenilink commented
You can still see the "add friend" and "block user" when you're already logged in as yourself.

2018-05-22 11:08 UTC, diogohmcruz requested changes
Ver @Evenilink comment

2018-05-22 19:30 UTC, diogohmcruz requested changes

2018-05-22 19:30 UTC, BlueDi commented on client/src/components/User.js
> +import { withCookies, Cookies } from 'react-cookie';
Há um warning que diz que não estás a usar o Cookies.
Ou te esqueces te de usar onde querias, ou é para tirar.

2018-05-24 22:18 UTC, BlueDi commented
@BSantos22 broken atm.

2018-05-25 08:20 UTC, diogohmcruz approved these changes

2018-05-25 09:04 UTC, merged