Feature/frontend/login (WIP)
ltrigo/mygrant pull request #7
Opened 2018-04-10 18:13 UTC by edgarlpassos

This PR reorganizes the structure of the src directory in the client.
Also adds Sass files, removing the CSS files that should be compiled afterwards.
Also adds (very basic) Login and Sign Up pages (frontend only).

**IMPORTANT: Do not delete this branch on merge!**

2018-04-11 16:53 UTC, diogohmcruz requested changes
Não está a passar no travis

2018-04-11 17:16 UTC, diogoseca commented
n é suposto o **yarn.lock** estar no gitignore?

2018-04-11 17:35 UTC, diogohmcruz requested changes

2018-04-11 17:35 UTC, BlueDi commented on .travis.yml
> +before_install: cd client && ./node_modules/.bin/node-sass ./src/scss -o ./src/css --output-style compressed && cd ..
as pastas node_modules não vão para o repositório e o travis não as deve criar

2018-04-11 18:45 UTC, BlueDi commented on client/src/components/App.js
> +import '../css/App.css';
se for executado localmente, isto não passa

2018-04-11 18:46 UTC, diogohmcruz requested changes

2018-04-11 18:46 UTC, BlueDi commented on client/src/components/App.js
> +import '../css/App.css';
se for executado localmente isto não passa

2018-04-13 09:00 UTC, diogohmcruz approved these changes

2018-04-13 09:01 UTC, merged